# Generated by Django 3.0.8 on 2020-08-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_auto_20200804_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.RoomType'),
        ),
    ]
