# Generated by Django 3.0.8 on 2020-08-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_auto_20200807_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
    ]
