# Generated by Django 3.0.8 on 2020-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0004_remove_room_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='details',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
