# Generated by Django 3.0.8 on 2020-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_roomtype_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
