# Generated by Django 3.0.8 on 2020-08-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0007_auto_20200809_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
