# Generated by Django 3.0.8 on 2020-08-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0008_auto_20200810_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
